# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-20 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('post_slug', models.CharField(max_length=100)),
                ('bookmarked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Clap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('post_slug', models.CharField(max_length=100)),
                ('liked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=1000)),
                ('photo', models.FileField(upload_to='images/')),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
