# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 04:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181120_1745'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100)),
                ('post_slug', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
            ],
        ),
    ]
