# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-22 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_unser_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='unser_names',
            new_name='user_names',
        ),
    ]
